apiVersion: v1
kind: Service
metadata:
  name: upstream
  namespace: traefik
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: v1
kind: Endpoints
metadata:
  name: upstream
  namespace: traefik
subsets:
  - addresses:
      - ip: UPSTREAM.IP.GOES.HERE
    ports:
      - port: 443

---
apiVersion: v1
kind: Service
metadata:
  name: upstream-health
  namespace: traefik
spec:
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083

---
apiVersion: v1
kind: Endpoints
metadata:
  name: upstream-health
  namespace: traefik
subsets:
  - addresses:
      - ip: UPSTREAM.IP.GOES.HERE
    ports:
      - port: 8083
