apiVersion: v1
kind: Service
metadata:
  name: maintenance
  labels:
    app: maintenance
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: maintenance
